In [49]:
import numpy as np

In [85]:
matrix = np.ones((5,5))
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [147]:
Betty = np.zeros((3, 3))
print(Betty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [149]:
Betty[1,1]=9
print(Betty)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [150]:
matrix[1:4,1:4] = Betty
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
